name = "WECOrules"
uuid = "28219d27-1ddc-405b-99a0-d6696678b826"
authors = ["Nicholas Ritchie <nicholas.ritchie@nist.gov> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
